// src/app/resume/page.tsx
import { Metadata } from "next";
import NextLink from "next/link";
import styles from "./resume.module.scss";

export const metadata: Metadata = {
  title: "Resume for Nate Radebaugh",
  description:
    "Hi I'm Nate Radebaugh. Manager, Software Solutions at BDO Digital in the western Chicago Suburbs. Graduate of Purdue University.",
  themeColor: "#e15227",
};

function Link(props: any) {
  const { href, ...rest } = props;

  return <NextLink href={href} className={styles.link} {...rest} />;
}

function ContentGroup({ label, children }) {
  return (
    <>
      <h2 className={styles.contentGroupLabel}>{label}</h2>
      <div className={styles.contentGroupContent}>{children}</div>
    </>
  );
}

interface EducationProps {
  degree: React.ReactNode;
  major: React.ReactNode;
  school: React.ReactNode;
  dates: React.ReactNode;
  location: React.ReactNode;
}

function Education({ degree, major, school, dates, location }: EducationProps) {
  return (
    <div className={styles.education}>
      <strong>{school}</strong>
      <span className={styles.location}>
        {location}, {dates}
      </span>
      <br />
      <span className={styles.educationDegrees}>
        {degree}, <em>{major}</em>
      </span>
    </div>
  );
}

interface EmploymentProps {
  position: React.ReactNode;
  dates: React.ReactNode;
  company: React.ReactNode;
  location: React.ReactNode;
  details?: React.ReactNode[];
}

function Employment({
  position,
  dates,
  company,
  location,
  details = [],
}: EmploymentProps) {
  return (
    <>
      <div className={styles.employment}>
        <h3 className={styles.companyName}>{company}</h3>
        <span className={styles.location}>{location}</span>
        <br />
        <h3 className={styles.position}>{position}</h3>
        <span className={styles.dates}>{dates}</span>
      </div>

      <ul className={styles.details}>
        {details.map((detail, i) => (
          <li key={i} className={styles.detail}>
            {detail}
          </li>
        ))}
      </ul>
    </>
  );
}

export default function Resume() {
  return (
    <div className={styles.resume}>
      <div>
        <div className={styles.name}>Nate Radebaugh</div>
        <div className={styles.contact}>
          530-628-3723 (mobile)
          <br />
          nate.radebaugh@outlook.com
          <br />
          <Link href="/">www.naterad.com</Link>
        </div>
      </div>

      <ContentGroup label="Skills:">
        <strong>Front Ends</strong> &ndash; React, Angular, JQuery, HTML, CSS.
        Bootstrap.
        <br />
        <strong>Back Ends</strong> &ndash; C# (MVC, API), Java (Spring Boot),
        SQL, PHP, C/C++.
        <br />
        <strong>Cloud Services</strong> &ndash; Azure, GitHub, AWS, Atlassin,
        Vercel.
        <br />
        <strong>Methodologies</strong> &ndash; Agile, Waterfall, or anywhere
        between &ndash; I&rsquo;m flexible!
      </ContentGroup>

      <ContentGroup label="Experience:">
        <Employment
          position={
            <>
              <strong>Manager</strong>, Software Development
            </>
          }
          dates="August 2021 - Present"
          company="BDO Digital"
          location="(Remote) Oak Brook, IL"
          details={[
            "App Frameworks focus area leader.",
            "Front End Technologies community leader.",
            "Solution architect/lead on multiple projects, writing technical docs, delegating tasks, and solving hard problems in variety of frameworks including Angular, React, .NET Core 3/5/6 and more.",
          ]}
        />
        <Employment
          position={
            <>
              <strong>Experienced Senior Associate</strong>, Software
              Development
            </>
          }
          dates="November 2020 - August 2021"
          company="BDO Digital"
          location="Oak Brook, IL"
          details={[
            "Scope management, budget estimation, release planning and scheduling, and delegation for multiple concurrent custom large-scale enterprise web applications for clients.",
          ]}
        />
        <Employment
          position={
            <>
              <strong>Senior Associate</strong>, Software Development
            </>
          }
          dates="December 2018 - November 2020"
          company="SWC Technology Partners (Aquired by BDO USA as BDO Digital)"
          location="Oak Brook, IL"
          details={[
            "Technical lead on C# .NET projects, coordinating technical implementations with more junior developers to successfully deliver quality applications.",
          ]}
        />
        <Employment
          position={
            <>
              <strong>Staff Consultant</strong>, Software Development
            </>
          }
          dates="May 2017 - December 2018"
          company="SWC Technology Partners"
          location="Oak Brook, IL"
          details={[
            "Individual contributor using C#, Java, and JQuery/Bootstrap to create enterprise web applications for clients companies.",
          ]}
        />
        <Employment
          position={
            <>
              <strong>Software Development Engineer 2</strong>, Windows System
              UI
            </>
          }
          dates="December 2015 - May 2017"
          company="Microsoft"
          location="Redmond, WA"
        />
        <Employment
          position={
            <>
              <strong>Software Development Engineer</strong>, Windows Phone
            </>
          }
          dates="August 2013 - December 2015"
          company="Microsoft"
          location="Redmond, WA"
        />
        <Employment
          position={
            <>
              <strong>Intern</strong>, Windows Phone
            </>
          }
          dates="Summer 2012"
          company="Microsoft"
          location="Redmond, WA"
        />
        <Employment
          position={
            <>
              <strong>Intern</strong>
            </>
          }
          dates="Summer 2011"
          company="Qualcomm"
          location="San Diego, CA"
        />
        <Employment
          position={
            <>
              <strong>Senior Software Developer</strong>
            </>
          }
          dates="Fall 2010 - Spring 2013"
          company="Purdue University ResNet (Internet Provider)"
          location="West Lafayette, IN"
        />
      </ContentGroup>

      <ContentGroup label="Education:">
        <Education
          degree="B.S."
          major={
            <>
              <strong>Computer Science</strong>, focus on Software Engineering
              and Programming Languages
            </>
          }
          dates="May 2013"
          location="West Lafayette, IN"
          school="Purdue University"
        />
      </ContentGroup>
    </div>
  );
}

// src/app/resume/resume.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import { ContentGroupComponent } from "./content-group/content-group.component";
import { EmploymentComponent } from "./employment/employment.component";
import { EducationComponent } from "./education/education.component";

@Component({
    selector: "app-resume",
    templateUrl: "./resume.component.html",
    styles: [
        `
      .resume {
        font-size: 14.4px;
        font-family: "Helvetica Neue", Arial;
        margin-left: auto;
        margin-right: auto;

        @media print, (min-width: 800px) {
          width: 8in;
        }

        br {
          clear: both;
        }
      }

      a.link {
        color: #f8f9fa;

        &:hover,
        &:focus {
          color: white;
        }
      }

      @media print {
        .resume {
          color: black;
        }

        a.link {
          color: #343a40;

          &:hover,
          &:focus {
            color: black;
          }
        }
      }

      div.name {
        font-size: 3em;
        font-weight: bold;
        display: inline-block;
        margin: 0;
        padding: 0;
      }

      div.contact {
        margin: 0;
        padding: 0;

        @media (max-width: 799px) {
          font-size: 1.2em;
          margin-top: 1em;
        }

        @media print, (min-width: 800px) {
          font-size: 1em;
          margin-top: 0;
          display: inline-block;
          float: right;
          text-align: right;
        }
      }
    `,
    ],
    imports: [
        RouterLink,
        ContentGroupComponent,
        EmploymentComponent,
        EducationComponent,
    ]
})
export class ResumeComponent {}

export default ResumeComponent;

<div class="resume">
  <title>Resume for Nate Radebaugh</title>

  <div>
    <div class="name">Nate Radebaugh</div>
    <div class="contact">
      530-628-3723 (mobile)
      <br />
      nate.radebaugh&#64;outlook.com
      <br />
      <a routerLink="/">www.naterad.com</a>
    </div>
  </div>

  <app-content-group label="Skills:">
    <strong>Front Ends</strong> &ndash; React, Angular, JQuery, HTML, CSS.
    Bootstrap.
    <br />
    <strong>Back Ends</strong> &ndash; C# (MVC, API), Java (Spring Boot), SQL,
    PHP, C/C++.
    <br />
    <strong>Cloud Services</strong> &ndash; Azure, GitHub, AWS, Atlassin,
    Vercel.
    <br />
    <strong>Methodologies</strong> &ndash; Agile, Waterfall, or anywhere between
    &ndash; I&rsquo;m flexible!
  </app-content-group>

  <app-content-group label="Experience:">
    <app-employment
      position="Experienced Manager"
      group="Software Development"
      dates="August 2023 - Present"
      company="BDO Digital"
      location="(Remote) Oak Brook, IL"
      [details]="[
        'Solution Architect'
      ]"
    />
    <app-employment
      position="Manager"
      group="Software Development"
      dates="August 2021 - August 2023"
      company="BDO Digital"
      location="(Remote) Oak Brook, IL"
      [details]="[
        'App Frameworks focus area leader.',
        'Front End Technologies community leader.',
        'Solution architect/lead on multiple projects, writing technical docs, delegating tasks, and solving hard problems in variety of frameworks including Angular, React, and .NET Core 8.'
      ]"
    />
    <app-employment
      position="Experienced Senior Associate"
      group="Software Development"
      dates="November 2020 - August 2021"
      company="BDO Digital"
      location="Oak Brook, IL"
      [details]="[
        'Scope management, budget estimation, release planning and scheduling, and delegation for multiple concurrent custom large-scale enterprise web applications for clients.'
      ]"
    />
    <app-employment
      position="Senior Associate"
      group="Software Development"
      dates="December 2018 - November 2020"
      company="SWC Technology Partners (Aquired by BDO USA as BDO Digital)"
      location="Oak Brook, IL"
      [details]="[
        'Technical lead on C# .NET projects, coordinating technical implementations with more junior developers to successfully deliver quality applications.'
      ]"
    />
    <app-employment
      position="Staff Consultant"
      group="Software Development"
      dates="May 2017 - December 2018"
      company="SWC Technology Partners"
      location="Oak Brook, IL"
      [details]="[
        'Individual contributor using C#, Java, and JQuery/Bootstrap to create enterprise web applications for clients companies.'
      ]"
    />
    <app-employment
      position="Software Development Engineer 2"
      group="Windows System UI"
      dates="December 2015 - May 2017"
      company="Microsoft"
      location="Redmond, WA"
    />
    <app-employment
      position="Software Development Engineer" group="Windows Phone"
      dates="August 2013 - December 2015"
      company="Microsoft"
      location="Redmond, WA"
    />
    <app-employment
      position="Intern"
      group="Windows Phone"
      dates="Summer 2012"
      company="Microsoft"
      location="Redmond, WA"
    />
    <app-employment
      position="Intern"
      dates="Summer 2011"
      company="Qualcomm"
      location="San Diego, CA"
    />
    <app-employment
      position="Senior Software Developer"
      dates="Fall 2010 - Spring 2013"
      company="Purdue University ResNet (Internet Provider)"
      location="West Lafayette, IN"
    />
  </app-content-group>

  <app-content-group label="Education:">
    <app-education
      school="Purdue University"
      location="West Lafayette, IN"
      dates="May 2013"
      degree="B.S."
      major="Computer Science"
      specialization="focus on Software Engineering and Programming Languages"
    />
  </app-content-group>
</div>
